add debug in yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -11,7 +11,7 @@ jobs:
 
     steps:
     - name: Checkout code
-      uses: actions/checkout@v4
+      uses: actions/checkout@v2
 
     - name: Run Docker command and get dynamic directory name
       id: docker_and_directory
@@ -38,12 +38,20 @@ jobs:
         echo "$(ls -td $DIRECTORY_NAME*)"
         echo "directory_name=$DIRECTORY_NAME" >> "$GITHUB_ENV"
 
+    - name: Verify dynamic directory existence
+      run: |
+        if [ -z "${{ env.directory_name }}" ]; then
+          echo "Dynamic directory not found. Exiting."
+          exit 1
+        else
+          echo "Dynamic directory found: ${{ env.directory_name }}"
+        fi
+
     - name: Upload artifact
-      uses: actions/upload-artifact@v4
+      uses: actions/upload-artifact@v2
       with:
         name: zimbra-package
-        path: ${{steps.docker_and_directory.outputs.directory_name}}*
-        compression-level: 0
+        path: ${{ env.directory_name }}/*.tgz
 
   release:
     if: startsWith(github.ref, 'refs/tags/')
@@ -51,13 +59,22 @@ jobs:
     needs: build
     steps:
       - name: Download packages
-        uses: actions/download-artifact@v4
+        uses: actions/download-artifact@v2
         with:
           name: zimbra-package
           path: zimbra-package
           
+      - name: Verify artifact existence
+        run: |
+          if [ ! -d "zimbra-package" ]; then
+            echo "Artifact directory not found. Exiting."
+            exit 1
+          else
+            echo "Artifact directory found: zimbra-package"
+          fi
+
       - name: Create release
         uses: ncipollo/release-action@v1
         with:
-          artifacts: "zimbra-package.zip"
+          artifacts: "zimbra-package/*.tgz"
           tag: ${{ github.ref_name }}
